name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
    - name: Restore dependencies
      run: nuget restore AdvancedRobloxArchival.sln
    - name: Build
      run: |
        msbuild.exe AdvancedRobloxArchival.sln
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
       name: Debug x64
       path: AdvancedRobloxArchival/bin/x64/Debug
